### ISSUE TITLE
Problem with create a Dockerfile

### ISSUE THREAD

**Issue by 3sky** [CapstoneLabs/slick#17]
It's my first issue ever, so hello everyone :) So..
I'm trying run `slick` in Docker, so I write some code:
```Dockerfile
FROM golang:alpine as builder
RUN mkdir /build
RUN apk add --update gcc go git mercurial \
    && go get github.com/CapstoneLabs/slick
ADD . /build/
WORKDIR /build
RUN go install -v 
FROM alpine
RUN apk --no-cache add ca-certificates
RUN adduser -S -D -H -h /app appuser
USER appuser
COPY --from=builder /build/main /app/
WORKDIR /app
EXPOSE 8080
CMD ["./main"]
```
But I get a Error:
> github.com/CapstoneLabs/slick
> src/github.com/CapstoneLabs/slick/bot.go:142:11: bot.Slack.SetDebug undefined (type *slack.Client has no field or method SetDebug)
> src/github.com/CapstoneLabs/slick/updateable.go:29:105: cannot use u.newFormattedMessage() (type string) as type slack.MsgOption in argument to u.reply.bot.Slack.UpdateMessage
 
So my question is how to build this app correctly?

**Comment by mattouille** [comment]
from `github.com/nlopes/slack@v0.4.0/slack.go`
```go
// SetDebug switches the api into debug mode
// When in debug mode, it logs various info about what its doing
// If you ever use this in production, don't call SetDebug(true)
func (api *Client) SetDebug(debug bool) {
	api.debug = debug
	if debug && logger == nil {
		SetLogger(log.New(os.Stdout, "nlopes/slack", log.LstdFlags|log.Lshortfile))
	}
}
```

I think the problem is that you're doing a `go get` on the `slick` package but not it's dependencies. This might look something like:

```dockerfile
RUN apk add --update gcc go git mercurial && go get ./...
```

This would fetch all dependencies for all packages within `slick`.

Let me know if that helps.

**Comment by 3sky** [comment]
I have made correctly working Dockerfile, container its only 18MB.

```Dockerfile
FROM golang:alpine as builder
RUN mkdir /slick
COPY . /slick
WORKDIR /slick
RUN apk add --update musl-dev gcc go git mercurial \
    && go get -d ./... 
RUN echo $GOPATH
WORKDIR /slick/example-bot
RUN go install -v 
FROM alpine
RUN apk --no-cache add ca-certificates
RUN adduser -S -D -H -h /app appuser
USER appuser
RUN id
COPY --from=builder /go/bin/example-bot /app/
COPY --from=builder --chown=appuser:nogroup /slick/plotbot.sample.conf /app/.slick.conf
WORKDIR /app 
RUN ls -la
RUN chmod 600 .slick.conf
CMD ["./example-bot"] 
```

It's build `example-bot` with `plotbot.sample.conf`, because I can't find other example :) 
So i could make PR for this as CI/CD's base (Travis Ci imho), close issue, and open another for working sample config.  `plotbot.sample.conf` output is : 

```commandline
$ docker logs slick
time="2018-10-17T11:00:26Z" level=error msg="Error in config JSON syntax." error="invalid character '\"' after object key:value pair"
time="2018-10-17T11:00:26Z" level=fatal msg="Error loading config file." error="invalid character '\"' after object key:value pair"
```

**Comment by mattouille** [comment]
Nice! Put in a PR
