### ISSUE TITLE
Migrate config from unmarshaling JSON to Viper

### ISSUE THREAD

**Issue by mattouille** [CapstoneLabs/slick#29]
This will give several different serialization options, specifically hitting the large ones (JSON, YAML, TOML)

Related to #28

**Comment by sethcenterbar** [comment]
@mattouille I'm a complete go noob and don't have any experience as a contributor, BUT i'm building a go CLI at work and have recent experience using viper. If you can point me to the file where you're currently unmarshaling JSON, I'd like to take a stab at implementing Viper.

**Comment by j-wil** [comment]
@sethcenterbar Thanks for contributing and don't worry about being new! 

I believe [line 295 in bot.go](https://github.com/CapstoneLabs/slick/blob/1a5af4c78479a0e9de7c708d3b5c7c54652a0adb/bot.go#L295-L311) will be a good place to start.

@mattouille and I spoke earlier and it looks like most of the config is handled using structs after its brought in so hopefully this wont be to big of a lift.

**Comment by j-wil** [comment]
@sethcenterbar  Also if you haven't make sure to check out the [contributing guidlines](https://github.com/CapstoneLabs/slick/blob/master/CONTRIBUTING.md)

**Comment by mattouille** [comment]
@sethcenterbar Here's the config structure the bot currently uses: https://github.com/CapstoneLabs/slick/blob/master/example-bot/plotbot.sample.conf

I can certainly help as well, so no worries there.

**Comment by HectorMalot** [comment]
Hi @mattouille , @j-wil , @sethcenterbar 
Perhaps I'll find a bit of time to help as well. Its Hacktoberfest after all.

Wanted to start a quick discussion on the potential solution here. `bot.LoadConfig` is called called from about 11 places. Every time its called it opens and reads the config file. The current setup uses the JSON marshaller's ability to throw away anything not specified in the given Struct to initialize various structs containing various parts of the configuration.

I see various options of implementing this:

1. (short and easy): modify [LoadConfig() in bot.go](https://github.com/CapstoneLabs/slick/blob/1a5af4c78479a0e9de7c708d3b5c7c54652a0adb/bot.go#L295-L311) to unmarshal using [Viper's unmarshal to Struct](https://github.com/spf13/viper#unmarshaling) capability. I think this also requires updating the various config structs with `mapstructure` comments. Upside: quick support for non-JSON formats

2. (medium): Load the config file on init. Then adjust the initialization of each of the config structs to use `Viper.Get()` calls to initialize their values.

In any case suggest to set a default config file (`config.toml|json|...`), searched for in the current dir and then the homedir. Also need update the example-bot with an example of overriding the config and a comment specifying what the default paths are.

Any thoughts on the above before I write any code? @sethcenterbar , also happy to contribute if you already started.

**Comment by mattouille** [comment]
@HectorMalot sounds like a good plan to me!

**Comment by sethcenterbar** [comment]
Dennis, work picked up this week and I haven't had a chance to work on it
so go for it!

**Comment by HectorMalot** [comment]
#57 proposed to close this one
