### ISSUE TITLE
Add tests for everything

### ISSUE THREAD

**Issue by mattouille** [CapstoneLabs/slick#5]
This will probably be an issue that needs to be split out but we can use this issue to garner more attention.

Currently, the bot is nearly 100% untested, from its core functionality to the plugins.

**Comment by ScreamingTaco** [comment]
I’m trying to work on writing go tests as part of Hacktoberfest. I’m pretty new to it, but I’ll try my hand at writing a few tests and submit a PR. Your choice to accept or not :)

**Comment by mattouille** [comment]
Honestly, at this point, even some tests are better than none. What I can say is I can collaborate with you to build the best possible tests we can.

Testing isn't easy, tends to be opinionated, and I don't really have any opinions with go testing yet; so your help is appreciated :)
